version: "2.4"
services:
  bkug:
    image: "heapy/bkug:${BKUG_VERSION}"
    container_name: "bkug"
    restart: "always"
    user: "${BKUG_SYSTEM_USER}"
    expose:
      - "8080"
    volumes:
      - bkug-data:/data
    environment:
      BKUG_OPTS: ${BKUG_OPTS}
      BKUG_ENV: ${BKUG_ENV}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: "40s"
volumes:
  bkug-data:
    driver: local
