import React from 'react';
import Menu from '../menu/menu.jsx';
import Gallery from '../gallery/gallery.jsx';

export default class Page extends React.Component {
    render() {
        return (
            <div>
                <Menu/>
                <div className="content container">
                    <h1>404: Page not found</h1>
                    <p className="lead">Sorry, we've misplaced that URL or it's pointing to something that doesn't
                        exist. <a href="/">Visit the home page</a> to see if you can find it manually. Thanks!</p>
                    <h3>Heads up!</h3>
                    <p>This is a basic 404 page for use with GitHub Pages. It's source code is not generated by
                        Jekyll.</p>

                    <Gallery/>
                </div>
            </div>
        );
    }
}
