import React from 'react';
import Menu from '../menu/menu.jsx';

export default class Page extends React.Component {
    render() {
        return (
            <div>
                <Menu/>
                <div className="content container">
                    <h1>404: Page not found</h1>
                    <p className="lead">Sorry, we've misplaced that URL or it's pointing to something that doesn't
                        exist. <a href="/">Visit the home page</a> to see if you can find it manually. Thanks!</p>
                    <h3>Heads up!</h3>
                    <p>This is a basic 404 page for use with GitHub Pages. It's source code is not generated by
                        Jekyll.</p>

                    <section className="c-gallery clearfix">
                        <div className="c-gallery__container c-gallery__container--product js-gallery">
                            <a href="/" data-size="1800x1800" className="c-gallery__item js-href-image js-gallery-item"
                               data-img-mx="http://placehold.it/1800x1800/E8117F/ffffff">
                                <picture className="c-gallery__img">
                                    <source srcSet="http://placehold.it/100x100/E8117F/ffffff" media="(min-width: 600px)"/>
                                    <img className="c-gallery__img" src="http://placehold.it/180x180/E8117F/ffffff" alt="MDN"/>
                                </picture>
                            </a>
                            <a href="/" data-size="1800x1800" className="c-gallery__item js-href-image js-gallery-item"
                               data-img-mx="http://placehold.it/1800x1800/E8117F/ffffff">
                                <picture className="c-gallery__img">
                                    <source srcSet="http://placehold.it/100x100/E8117F/ffffff" media="(min-width: 600px)"/>
                                    <img className="c-gallery__img" src="http://placehold.it/180x180/E8117F/ffffff" alt="MDN"/>
                                </picture>
                            </a>
                            <a href="/" data-size="1800x1800" className="c-gallery__item js-href-image js-gallery-item"
                               data-img-mx="http://placehold.it/1800x1800/E8117F/ffffff">
                                <picture className="c-gallery__img">
                                    <source srcSet="http://placehold.it/100x100/E8117F/ffffff" media="(min-width: 600px)"/>
                                    <img className="c-gallery__img" src="http://placehold.it/180x180/E8117F/ffffff" alt="MDN"/>
                                </picture>
                            </a>
                            <a href="/" data-size="1800x1800" className="c-gallery__item js-href-image js-gallery-item"
                               data-img-mx="http://placehold.it/1800x1800/E8117F/ffffff">
                                <picture className="c-gallery__img">
                                    <source srcSet="http://placehold.it/100x100/E8117F/ffffff" media="(min-width: 600px)"/>
                                    <img className="c-gallery__img" src="http://placehold.it/180x180/E8117F/ffffff" alt="MDN"/>
                                </picture>
                            </a>
                            <a href="/" data-size="1800x1800" className="c-gallery__item js-href-image js-gallery-item"
                               data-img-mx="http://placehold.it/1800x1800/E8117F/ffffff">
                                <picture className="c-gallery__img">
                                    <source srcSet="http://placehold.it/100x100/E8117F/ffffff" media="(min-width: 600px)"/>
                                    <img className="c-gallery__img" src="http://placehold.it/180x180/E8117F/ffffff" alt="MDN"/>
                                </picture>
                            </a>
                            <a href="/" data-size="1800x1800" className="c-gallery__item js-href-image js-gallery-item"
                               data-img-mx="http://placehold.it/1800x1800/E8117F/ffffff">
                                <picture className="c-gallery__img">
                                    <source srcSet="http://placehold.it/100x100/E8117F/ffffff" media="(min-width: 600px)"/>
                                    <img className="c-gallery__img" src="http://placehold.it/180x180/E8117F/ffffff" alt="MDN"/>
                                </picture>
                            </a>
                            <a href="/" data-size="1800x1800" className="c-gallery__item js-href-image js-gallery-item"
                               data-img-mx="http://placehold.it/1800x1800/E8117F/ffffff">
                                <picture className="c-gallery__img">
                                    <source srcSet="http://placehold.it/100x100/E8117F/ffffff" media="(min-width: 600px)"/>
                                    <img className="c-gallery__img" src="http://placehold.it/180x180/E8117F/ffffff" alt="MDN"/>
                                </picture>
                            </a>
                            <a href="/" data-size="1800x1800" className="c-gallery__item js-href-image js-gallery-item"
                               data-img-mx="http://placehold.it/1800x1800/E8117F/ffffff">
                                <picture className="c-gallery__img">
                                    <source srcSet="http://placehold.it/100x100/E8117F/ffffff" media="(min-width: 600px)"/>
                                    <img className="c-gallery__img" src="http://placehold.it/180x180/E8117F/ffffff" alt="MDN"/>
                                </picture>
                            </a>
                        </div>
                    </section>
                </div>
            </div>
        );
    }
}
